config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "flats#index"
  resources :flats do
    collection do
      get "search", to: "flats#search"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, presence: true
  validates :price_per_night, :number_of_guest, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    params['query'].nil? ? @flats = Flat.all : @flats = Flat.where("name LIKE '%#{params['query']}%")
    @query = params['query']
    @total = Flat.all.length
    @search_msg = ""
    unless @query.nil?
      @search = "We looked for #{@query}. We found #{@flats.length} flats out of #{@total}"
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to_flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_flat
    @flat = Flat.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="flat-form">

  <%= simple_form_for(@flat) do |f| %>

    <div class="form-control">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night, :input_html => { type: "number" } %>
      <%= f.input :number_of_guest, :input_html => { type: "number"} %>
      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-primary" %>
        <%= link_to 'Back', flats_path, class: "btn btn-warining" %>
      </div>
    </div>


  <% end %>
</div>

app/views/flats/edit.html.erb
<div class="container pt-4">
  <h1>Modify the property details</h1>

<%= render 'form', flat: @flat %>

</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <h1 class=mb-2">Availables Flats</h1>
  <p class="mp-1"><%= @search_msg %></p>
<d class="row d-flex justify-content-between p-3">
  <% @flats.each do |flat| %>
  <div class="col-3 card mx-2 overflow-auto d-flex flex-column justify-content-around mb-3 bg-light text-dark bg-grey" style="height: 400px;">"
    <div class="bg-light">
      <div class="">
        <img src="<%= flat.image %>" alt="pic" class="img-fluid" >
        <h3 class="my-3" style="font-size: 20px"><%= flat.name %></h3>
        <p><%= flat.address %></p>
      </div>
      <div class="d-flex justify-content-between my-2">
        <p><i class="fas fa-users"></i> <%= flat.number_of_guest %></p>
        <p><i class="fab fa-ethereum"></i> <%= flat.price_per_night %></p>
      </div>
    </div>
      <div class="d-flex justify-content-between align_items_center">
        <p><%= link_to "Information about the Property", flat_path(flat), class: "bg-info text-white" %></p><br>
        <p><%= link_to "Modify", edit_flat_path(flat), class: "bg-info text-white" %></p><br>
        <p><%= link_to "Delete", flat, class: "bg-danger text-white", method: :delete, data: { confirm: "Are you sure you want to delete?" } %></p>
      </div>
    </div>
    <% end %>
    </d>
  </div>

app/views/flats/new.html.erb
<div class="container pt-4">
  <h1>Add a new Property</h1>


<%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url(<%= @flat.image %>)"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="flat-show-card">
      <h1><%= @flat.name %></h1>
      <p class="flat-show-address"><%= @flat.address %></p>
    </div>
    <div class="flat-show-card">
      <h2>Interested by the Property? Come here..</h2>
      <p><%= @flat.description %></p>
      <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=10 Clifton Gardens London W9 1DT&amp;zoom=13&amp;scale=2&amp;size=1000x1000&amp;maptype=roadmap&amp;markers=color:red%7C10 Clifton Gardens London W9 1DT&amp;key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
    </div>

    <div class="clo-4">
      <div class="flat-show-card">
        <h4>Book the place</h4>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="25/07/2019" aria-label="Username" aria-describebdy="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="07/08/2019" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h2>Details</h2>
        <div class="d-flex align_items_start">
          <div class="d-flex">
            <i class="fas fa-users mr-1"></i><span><%= @flat.number_of_guest %></span>
          </div>
          <div class="d-flex ml-3">
            <i class="fas fa-ethereum"></i><span><%= @flat.price_per_night %></span>
          </div>
        </div>
      </div>

      <div class="flat-show-card">
        <div class="flex-align">
          <h5 class="no-mb">Share</h5>

          <div class="flex">
            <i class="fas fa-facebook"></i>
            <i class="fa fa-twitter-square fa-2x mr-2"></i>
            <i class="fa fa-pinterest-square fa-2x mr-2"></i>
          </div>
        </div>
      </div>

      <div class="flat-show-card">
        <div class="flex-align">
          <h5 class="no-mb">Back to menu</h5>
            <div>
              <%= link_to "Back to menu", flats_path, class: "bg-info text-white" %>
            </div>
         </div>

      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-white">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= @query %>">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
          </form>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>